### ISSUE TITLE
load packages directly from github

### ISSUE THREAD

**Issue by antonum** [intersystems-community/zpm#101]
add support for loading data from github repo:

`zpm: USER>load https://github.com/user/repo.git`

If repo is public and contains /module.xml - load it directly from github. It may be implemented with %Net.HttpRequest or $zf(-100,"","git",.args). $zf approach might allow for interaction with private repos, but requires installing git on the host.

**Comment by SergeyMi37** [comment]
is this implemented i think it can be closed?
