### ISSUE TITLE
ZPM install fails (v 0.2.2)

### ISSUE THREAD

**Issue by jtsalten** [intersystems-community/zpm#104]
I'm using it with Windows 10 Pro and IRIS 2020.1

Trying with last version of ZPM. I import/compile through Studio, classes' compiling seems to work but the installation fails with module.xml malformed error. 
After that, I can use zpm commands in Terminal and even seems to install packages... but after installing whatever package (I tried several of them), I got the same error message about malformed module.xml.
As an example, I've tried to install the JSON Web Token generator and following the instructions to test:
zpm: USER>list
blocksexplorer 2.2.1
sys-perf-restapi 1.0.5
webterminal 4.9.2
 
zpm: USER>install jwt-generator
 
ERROR #5001: module.xml is malformed.
ERROR #5001: module.xml is malformed.
zpm: USER>quit
USER>set val = 3600
USER>Set jwt = ##class(dc.auth.jwt.JWTGenerator).generate("MySecretKey",val)     
SET jwt = ##CLASS(dc.auth.jwt.JWTGenerator).generate("MySecretKey",val)
^
<CLASS DOES NOT EXIST> *dc.auth.jwt.JWTGenerator

**Comment by nsolov** [comment]
Problem occurs with 
locale  espw (Spanish, Spain, Unicode)

**Comment by ZitRos** [comment]
[Related case](https://github.com/intersystems-community/webterminal/issues/136#issuecomment-636691808) with WebTerminal installation.

**Comment by evshvarov** [comment]
@jtsalten , this is done with 0.2.4, check, please
