### ISSUE TITLE
Unittest conflicts during installation

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/zpm#112]
if you install package-example and csvgen you get unittest check fail

**Comment by nsolov** [comment]
1. test doesn't start automatically during installation
2. with `csvgen test` test fails
the problem is "ERROR #5007: Directory name '/irisdev/app/data/' is invalid"
3.  the conflict could occur only when in two packages you use the same resource

**Comment by evshvarov** [comment]
The issue was in the package names - tests are included into the package and should obey the naming agreement
