### ISSUE TITLE
problem with duplicate package name

### ISSUE THREAD

**Issue by rcemper** [intersystems-community/zpm#123]
I typically put my demo classes n Package Z.*
in module.xml is rather similar:
      <SourcesRoot>src</SourcesRoot>
       <Resource Name=**"Z.PKG"**/>
using the same package name in different projects caused this during installation:
> ERROR #5001: Resource 'Z.PKG' is already defined as part of module 'remote-server-control'; cannot also be listed in module 'obj-dump'

is it a bug?
how can I have the same package in more than 1 project ?

in that simple case, I just renamed 1 of it.
but that's not optimal as had to change all descriptions and comments.
pls. advise !

**Comment by daimor** [comment]
That’s not the issue of zpm, just objectscript. In short you have to use different package names for every your different project
Look here, Evgeny already raised this
https://community.intersystems.com/post/objectscript-package-manager-naming-convention

**Comment by rcemper** [comment]
Thanks for your quick reply.
it's acceptable for new code in new projects
for existing examples it would mean to rewrite & test a lot of code and the related documentation. 

BTW is there an option to have ?
> " <Resource Name=""Z.democlass.CLS.""/> "

**Comment by rcemper** [comment]
I tried (probaly missimg something)  but i seemed not to be pleased by **Z.**name.CLS

**Comment by daimor** [comment]
Sure, you can define exact class, if you like 

Zpm, when package module, it exports everything as described, so, if you say Z.pkg it will package all the class in the package, same for uninstalling

**Comment by rcemper** [comment]
Thanks. That's a chance to keep my puzzles together in a common basket !!
GREAT!
