### ISSUE TITLE
conflict of PKG names across different modules

### ISSUE THREAD

**Issue by rcemper** [intersystems-community/zpm#126]
out of the experience: every project in ZPM needs its personal package.

otherwise, you may see this:

ERROR #5001: Resource 'rcc.PKG' is already defined as part of module 'echoserver-wsock-iris'; cannot also be listed in module 'iris-internal-websocket-client'
ERROR #6315: File Errors reporting importing XML subelement in file  'C:\InterSystems\IRIS\mgr\.modules\USER\iris-internal-websocket-client\1.0.0\module.xml', at line'3', offset '55'. skipping this

**Comment by timleavitt** [comment]
This is a feature. Any installed module should be uninstallable. If the same thing is listed as part of multiple packages than that won't be the case.

You can instead list classes individually, or (if you are reusing some classes) list a dependency on the module that they authoritatively belong in.

**Comment by rcemper** [comment]
What about dependencies?
I didn't try as the raw process was complex enough causing multiple edit cycles
