### ISSUE TITLE
Make a convenient call for available modules to install

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/zpm#13]
E.g.
list -remote
to display what's available on the current registry

**Comment by nsolov** [comment]
now "list" is an alias for list-installed

I suggest replacing the "list-installed" command with

list : command
and modifiers:
modifier -installed ("list -installed" or "list -i") - displays installed modules
modifier -available("list -available" or "list -a") - displays what's available on the current registry

**Comment by evshvarov** [comment]
Agreed

ср, 29 янв. 2020 г. в 14:06, Nikolay Soloviev <notifications@github.com>:

**Comment by timleavitt** [comment]
There's repo -list-modules to display what's available on the current registry.

**Comment by evshvarov** [comment]
'search' synonym command is introduced to show available modules on the current registry with 1.0.6 release
