### ISSUE TITLE
When uninstalling the module, the mapping package is not removed

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems-community/zpm#171]

**Comment by SergeyMi37** [comment]
Hi @timleavitt 
Tell me why mapping is created for packages when installing a module? What's the point of this ?

**Comment by isc-kiyer** [comment]
@SergeyMi37 The intention is to ensure that the code of the module is loaded into the default database for the current namespace

**Comment by daimor** [comment]
It's actually says nothing, it should be done by IRIS itself without any extra mapping

**Comment by isc-kiyer** [comment]
@daimor That is true only if there are no existing mappings for the namespace that could match the resources for the module being loaded. The mapping creation is a redundancy to ensure that existing mappings are overridden to force the code to go to the default database.

**Comment by daimor** [comment]
So, if namespace already has some mapping which would override default behavior will mean that package will be installed incorrectly and will not work, so it make no sense at all

**Comment by isc-kiyer** [comment]
Sorry I am confused by your statement. If the namespace has some mappings in place already, the package manager ensures that those mappings do not interfere with installation of the package by creating its own mappings, which will override the existing mappings of the namespace. This ensures that the package is installed correctly.
When I said it is a redundancy, I meant that more often than not, such pre-existing mappings would not match against resources of the package being installed, resulting in the resources getting loaded into the default database automatically (handled by IRIS).

**Comment by daimor** [comment]
Sorry, yes, my mistake.

So, just as a conclusion, we can remove such behavior from zpm?

**Comment by isc-kiyer** [comment]
I would recommend making it optional (via a -D modifier, say if -DMapping=1) rather than removing it

**Comment by daimor** [comment]
At the moment it have the issue, with clean up during uninstall, support for wildcard.

And even having it as an option in this place, will mean that we still have to care about it, and realize missing functionality.

**Comment by timleavitt** [comment]
I think removing the functionality would solve more problems than it creates. Might be worth a backlog issue to reinstate it as an optional behavior with all the required bookkeeping included.

**Comment by timleavitt** [comment]
(This is something that matters a lot more in the original use cases in HealthShare than it does for community use cases.)

**Comment by SergeyMi37** [comment]
Problem solved 
https://github.com/intersystems-community/zpm/pull/221
+ #211
