### ISSUE TITLE
Can't install module on intersystemsdc/iris-community:2020.4.0.524.0-zpm and zpm 0.2.10

### ISSUE THREAD

**Issue by grongierisc** [intersystems-community/zpm#197]
On this image and running container intersystemsdc/iris-community:2020.4.0.524.0-zpm.

I can search : 
zpm: USER>search csvgen-ui
registry https://pm.community.intersystems.com:
csvgen-ui 1.0.2
But i can't install : 
zpm: USER>install csvgen-ui

ERROR #5001: Repository 'registry' is unavailable.

Am I doing something wrong ?

**Comment by nsolov** [comment]
I can't reproduce the problem

Please run command
`repo -list`
what does it display?

**Comment by grongierisc** [comment]
zpm: USER>repo -list


registry
        Source:         https://pm.community.intersystems.com
        Enabled?        Yes
        Available?      Yes
        Use for Snapshots?      Yes
        Use for Prereleases?    Yes

zpm: USER>install csvgen

ERROR #5001: Repository 'registry' is unavailable.

To reproduce : 
docker run --rm -d  -p 1972:1972/tcp -p 2188:2188/tcp -p 52773:52773/tcp -p 53773:53773/tcp -p 54773:54773/tcp intersystemsdc/irishealth-community:2020.4.0.524.0-zpm
docker exec -it <containerid> bash
iris session iris
zpm "install csvgen"

Host : MacOs BigSur 11.1
Docker desktop : 
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by evshvarov** [comment]
Looks like a network issue which we do not handle in zpm.
this works on my side too.

**Comment by evshvarov** [comment]
zpm: USER>ver


%SYS> zpm 0.2.12

 Locally installed zpm-registry not found

https://pm.community.intersystems.com - 0.0.2

zpm: USER>

**Comment by nsolov** [comment]
Please install ZPM beta version ZPM https://github.com/intersystems-community/zpm/releases/tag/v0.2.13-beta.2
and try 
It should work

If yes, we'll update images
