### ISSUE TITLE
Can't install on Iris for Health

### ISSUE THREAD

**Issue by grongierisc** [intersystems-community/zpm#2]
Hi,

I try to install zpm on iris for health with those commands : 

- cd /tmp

- wget -q https://pm.community.intersystems.com/packages/zpm/latest/installer -O zpm.xml

- iris session irishealth

- USER>Do $system.OBJ.Load("/tmp/zpm.xml","ck")

Error : 

>Compiling routine %ZPM.PackageManager.Developer.ResourceReferenceAttributes.1
ERROR #6281: XMLTYPE of class %ZPM.PackageManager.Developer.Processor.CSPApplication must be able to differentiate child classes of %Installer.Activity.
  > ERROR #5090: An error has occurred while creating projection %ZPM.PackageManager.Developer.Processor.CSPApplication:XMLEnabled.
Detected 1 errors during compilation in 1.812s.
>ERROR #6281: XMLTYPE of class %ZPM.PackageManager.Developer.Processor.CSPApplication must be able to differentiate child classes of %Installer.Activity.
  > ERROR #5090: An error has occurred while creating projection %ZPM.PackageManager.Developer.Processor.CSPApplication:XMLEnabled.
Detected 1 errors during load.
2019-09-30 11:35:43 0 %ZPM.Installer: ERROR #6281: XMLTYPE of class %ZPM.PackageManager.Developer.Processor.CSPApplication must be able to differentiate child classes of %Installer.Activity.
  > ERROR #5090: An error has occurred while creating projection %ZPM.PackageManager.Developer.Processor.CSPApplication:XMLEnabled.
2019-09-30 11:35:43 0 %ZPM.Installer: Installation failed at 2019-09-30 11:35:43
2019-09-30 11:35:43 0 %Installer: Elapsed time 4.49325s
Time spent 4.519202
Load finished successfully.

Tested on : 

- IRIS for UNIX (Ubuntu Server LTS for x86-64 Containers) 2019.2.0S (Build 260U) Thu Jun 13 2019 01:59:29 EDT

- IRIS for UNIX (Apple Mac OS X for x86-64) 2019.1.0S (Build 111U) Wed Jan 16 2019 00:31:57 EST

**Comment by daimor** [comment]
well, I managed to reproduce the error on docker version `intersystems/irishealth-community:2019.3.0.309.0`, so, later I'll try to fix it.

**Comment by lscalese** [comment]
Hello @daimor,
I've the same problem.
There is two %Installer.Activity subclasses with the same XMLTYPE and XMLNAME parameters : 

1. %ZHSLIB.PackageManager.Developer.Processor.CSPApplication.

I think, it would be easily fixed by a simple change

**Comment by daimor** [comment]
Version 0.1.0 of ZPM should now work on IRIS for Health as well
