### ISSUE TITLE
dash in package name prevents install

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/zpm#231]
```
zpm "install samples-bi"
```

does not work.

![image](https://user-images.githubusercontent.com/5127457/120379772-e7ccd100-c328-11eb-84ca-9039f784ef93.png)

Tested on:  `intersystemsdc/iris-community:2020.4.0.547.0-zpm`

**Comment by eduard93** [comment]
Is there a COS way to call install as a workaround?

**Comment by evshvarov** [comment]
Check your ZPM version, use the latest if possible
