### ISSUE TITLE
zpm load from github does not work

### ISSUE THREAD

**Issue by daimor** [intersystems-community/zpm#232]
```
zpm:CONDUIT>load https://github.com/timleavitt/forgery/ -v

Create tempory directory /usr/irissys/mgr/Temp/6590039389210874/
cd /usr/irissys/mgr/Temp/6590039389210874/ && git clone https://github.com/timleavitt/forgery/

/usr/irissys/mgr/Temp/6590039389210874//Cloning into 'forgery'...


ERROR #6901: XSLT XML Transformer Error: invalid document structure in  at line 1 offset 1
```
while it's cloned correctly
```
CONDUIT>!find /usr/irissys/mgr/Temp/6590039389210874/
/usr/irissys/mgr/Temp/6590039389210874/
/usr/irissys/mgr/Temp/6590039389210874/forgery
/usr/irissys/mgr/Temp/6590039389210874/forgery/module.xml
/usr/irissys/mgr/Temp/6590039389210874/forgery/README.md
.....

CONDUIT>!cat /usr/irissys/mgr/Temp/6590039389210874/forgery/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<Export generator="Cache" version="25">
<Document name="Forgery.ZPM"><Module>
  <Name>Forgery</Name>
  <Version>1.1.3</Version>
  <Packaging>module</Packaging>
  <Resource Name="Forgery.PKG" />
  <LifecycleClass>Module</LifecycleClass>
</Module>
</Document></Export>
```
and even load for this folder works well
```
zpm:CONDUIT>load /usr/irissys/mgr/Temp/6590039389210874/forgery   

[forgery]       Reload START
[forgery]       Reload SUCCESS
[forgery]       Module object refreshed.
[forgery]       Validate START
[forgery]       Validate SUCCESS
[forgery]       Compile START
[forgery]       Compile SUCCESS
[forgery]       Activate START
[forgery]       Configure START
[forgery]       Configure SUCCESS
[forgery]       Activate SUCCESS

```

**Comment by SergeyMi37** [comment]
There was a mistake in your call.
Such an error call does not cause
load https://github.com/timleavitt/forgery.git -v
 
cd D:\InterSystems\IRISPY\mgr\Temp\65903642863750981\ && powershell Expand-Archive -LiteralPath D:\InterSystems\IRISPY\mgr\Temp\65903642863750981\tmp.zip -DestinationPath D:\InterSystems\IRISPY\mgr\Temp\65903642863750981\                    
[forgery]       Reload START (D:\InterSystems\IRISPY\mgr\Temp\65903642863750981\forgery-master\)
[forgery]       Reload SUCCESS
[forgery]       Module object refreshed.
[forgery]       Validate START
[forgery]       Validate SUCCESS
[forgery]       Compile START
[forgery]       Compile SUCCESS
[forgery]       Activate START
[forgery]       Configure START
[forgery]       Configure SUCCESS
[forgery]       MakeDeployed START
[forgery]       MakeDeployed SUCCESS
[forgery]       Activate SUCCESS
zapm:USER>

**Comment by daimor** [comment]
But, git cloned it correctly, so, I suppose, we can support this way as well
