### ISSUE TITLE
Error (hspm) Error installing extension MAC

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems-community/zpm#239]
zpm:IRIS>iris-test>USER>ver

%SYS> zpm 0.2.14

zpm:IRIS>iris-test>USER>install zpmshow

[zpmshow]       Reload START
[zpmshow]       Reload SUCCESS
[zpmshow]       Module object refreshed.
[zpmshow]       Validate START
[zpmshow]       Validate SUCCESS
[zpmshow]       Compile START
[zpmshow]       Compile SUCCESS
[zpmshow]       Activate START
[zpmshow]       Configure START
[zpmshow]       Configure SUCCESS
[zpmshow]       Activate SUCCESS
zpm:IRIS>iris-test>USER>

zpm

zpm:iris-test>IRIS20203>USER>ver
%SYS> zpm 0.2.15-de.228.229

zpm:iris-test>IRIS20203>USER>install zpmshow

[zpmshow]       Reload START (/opt2/isc/iris20203/mgr/.modules/USER/zpmshow/1.0.2/)
[zpmshow]       Reload FAILURE
ERROR! Cannot open file '/opt2/isc/iris20203/mgr/.modules/USER/zpmshow/1.0.2/src/zpmshow.rtn'

**Comment by daimor** [comment]
solved
