### ISSUE TITLE
Error (hspm) If during the installation of a module with dependencies an error occurred and the module was not installed, then the dependent modules should not be installed either.

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems-community/zpm#240]
If during the installation of a module with dependencies an error occurred and the module was not installed, then the dependent modules should not be installed either.

Previously, this was solved by rolling back the transaction.

**Comment by evshvarov** [comment]
We don't use transactions anymore?

**Comment by daimor** [comment]
We still have transactions, but they should not be so wide. Dependent modules should not be reverted if they were successfully installed.

**Comment by evshvarov** [comment]
In fact, I'm OK with that - the building process more and more goes to
container-based where you don't care very much about what is installed -
you jut rebuild it.

**Comment by daimor** [comment]
transactions supposed to be as small as possible, to cover just only what needs to be covered, then commit or rollback.
too big transactions may cause issues, for instance, if a module has many dependencies.

**Comment by evshvarov** [comment]
makes sense

**Comment by SergeyMi37** [comment]
ok
