### ISSUE TITLE
Error (hspm) ERROR! Storage on class ... modified by storage compiler, developer should have run ^build to make sure all storage is updated correctly and saved to Perforce

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems-community/zpm#241]
eg 
zpm:iris-test>IRIS20203>BITMAPADOPTION>install collection-index-and-query

[collection-index-and-query]    Reload START (/opt2/isc/iris20203/mgr/.modules/BITMAPADOPTION/collection-index-and-query/1.0.1/)
[collection-index-and-query]    Reload SUCCESS
[collection-index-and-query]    Module object refreshed.
[collection-index-and-query]    Validate START
[collection-index-and-query]    Validate SUCCESS
[collection-index-and-query]    Compile START
[collection-index-and-query]    Compile FAILURE
ERROR! Storage on class rcc.IC.ItemList modified by storage compiler, developer should have run ^build to make sure all storage is updated correctly and saved to Perforce

zpm:iris-test>IRIS20203>BITMAPADOPTION>install bitmap-adoption

[bitmap-adoption]       Reload START (/opt2/isc/iris20203/mgr/.modules/BITMAPADOPTION/bitmap-adoption/1.0.4/)
[bitmap-adoption]       Reload SUCCESS
[bitmap-adoption]       Module object refreshed.
[bitmap-adoption]       Validate START
[bitmap-adoption]       Validate SUCCESS
[bitmap-adoption]       Compile START
[bitmap-adoption]       Compile FAILURE
ERROR! Storage on class Bmap.Address modified by storage compiler, developer should have run ^build to make sure all storage is updated correctly and saved to Perforce

json-snapshot, native-api-objectscript, posts-and-tags, remote-server-control, sql-batch-outbound-adaptor, sync-dstime

**Comment by daimor** [comment]
That package has a Persistent class without any Storage defined, and the error says about it.
I agree with it and don't see any reasons to change this behavior. 
The author should define Storage, and publish a new version.

**Comment by bdeboe** [comment]
Many of our samples (e.g. [Samples-BI](https://github.com/intersystems/Samples-BI)) have no storage defined, because they intentionally try to be as simple as can be. Also, the errors aren't raised with a simple `$SYSTEM.OBJ.LoadDir()` or similar (nor with earlier versions of zpm).

I agree this new behaviour is a safe default, but am curious if there'd be a way to be more lenient through some package setting.

**Comment by SergeyMi37** [comment]
This is not a bug for the new version.
