### ISSUE TITLE
Misbehavior, install without module installs webterminal

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems-community/zpm#243]
zpm:USER>
 
zpm:USER>install
 
[webterminal]   Reload START (D:\InterSystems\IRISTEST\mgr\.modules\USER\webterminal\4.9.2\)
[webterminal]   Reload SUCCESS
[webterminal]   Module object refreshed.
[webterminal]   Validate START
[webterminal]   Validate SUCCESS
[webterminal]   Compile START
Installing WebTerminal application to USER

**Comment by evshvarov** [comment]
LOL ) Yeaster egg?

**Comment by SergeyMi37** [comment]
Something like that). If you don't know what to install, put the most popular one
