### ISSUE TITLE
Add a flag allowing to use the resources of old modules in new modules

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems-community/zpm#287]
Sometimes in new ZPM modules you need to use the resources of old modules. It is now prohibited to do this. The message is displayed:
ERROR! Resource '/csp/apptools (/apptools)' is already defined as part of module 'apptools-admin' as '/web'; cannot also be listed in module 'useroles'
  > ERROR #6315: Errors reporting importing XML subelement in file '/usr/irissys/mgr/Temp/6607371240844153/module.xml' at line '3' offset '33', skippingthis item.

I propose to introduce a flag allowing to do this.
In this case, the program will display a warning message.

**Comment by isc-tleavitt** [comment]
If this change is made, uninstallation of packages needs to take into account that multiple packages may define/use the same resources, and the resource shouldn't be deleted until all packages using it have been uninstalled.

**Comment by SergeyMi37** [comment]
Agree.
