### ISSUE TITLE
Default MAXLEN (50) for Invoke's Arg values is too small

### ISSUE THREAD

**Issue by jonlent** [intersystems-community/zpm#333]
Line 14 of %ZPM.PackageManager.Developer.InvokeReference reads:
~~~
Property Arg As list Of %String(XMLNAME = "Arg", XMLPROJECTION = "ELEMENT");
~~~
And should at least be:
~~~
Property Arg As list Of %String(MAXLEN = 255, XMLNAME = "Arg", XMLPROJECTION = "ELEMENT");
~~~

**Justification:**
Some Import tasks that take files paths as arguments can easily exceed the default 50 character limit of the property. The result is that the load or install fails with a validation error on "Arg"

**Comment by daimor** [comment]
solved
