### ISSUE TITLE
Update %ZPM.PackageManager.Developer.Utils:RunCommandViaZF (and its callers) to use $zf(-100)

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems-community/zpm#336]
See discussion in https://github.com/intersystems/git-source-control/discussions/203#discussioncomment-3378758 for background.

%ZPM.PackageManager.Developer.Utils:RunCommandViaZF uses $zf(-1) which is deprecated and less secure than $zf(-100).

**Comment by daimor** [comment]
`RunCommand` with `$zf(-100)` implemented
@isc-tleavitt closing?
