### ISSUE TITLE
Reimplement %ZPM.PackageManager.Developer.File:CopyDir to not use ROBOCOPY on Windows

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems-community/zpm#337]
Generally, copying files shouldn't require %System_Callout:USE. As it stands, it does.

For background, see https://github.com/intersystems/git-source-control/discussions/203#discussioncomment-3378758

**Comment by daimor** [comment]
Any Ideas why it's even used ROBOCOPY?
in CopyDir and even RemoveDirectoryTree
On Unix just used IRIS methods, but for Windows is a special implementation

**Comment by isc-tleavitt** [comment]
I believe the motivation was to get around directory length issues on Windows. see e.g. https://stackoverflow.com/questions/29865863/how-to-move-folder-files-with-path-names-255-characters-in-windows-8-1

**Comment by isc-tleavitt** [comment]
Actually that's a good reason to (perhaps) keep using robocopy. :(

**Comment by daimor** [comment]
It means, that `##class(%Library.File).RemoveDirectoryTree()` can't solve it?

**Comment by isc-tleavitt** [comment]
Correct.
