### ISSUE TITLE
add to system requirements in module.xml on IRIS for Health or HealthShare

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems-community/zpm#340]

**Comment by daimor** [comment]
@isc-tleavitt I don't see any profits from doing that exact check for Health, I'm sure that we need to check the exact Health component to be installed or activated, for instance, FHIR. I can probably add a check for FHIR, but no idea what else would need, I see some other packages, which may require something else, and fails during installation.

**Comment by isc-tleavitt** [comment]
I think for HealthShare we might want to restrict based on namespace type - e.g., hub, access gateway, edge gateway. This should just be ##class(HS.Util.Installer.ConfigItem).TypeGetStored($Namespace).

**Comment by isc-tleavitt** [comment]
(and certainly we should be able to require IRIS for Health)

**Comment by bourette** [comment]
I would think you would want a collection, for instance, many IHE components would be HealthConnect, or I4H, or UCR, but some would be only I4H or UCR.

**Comment by isc-kiyer** [comment]
We would need a public API to expose clear versions of HS components to indicate requirements on things like access or edge gateways. We can however, list requirements on the various library databases (HSLIB, VIEWERLIB etc.) which is exposed through `%ZHSLIB.HealthShareMgr:ComponentVersion()`

**Comment by SergeyMi37** [comment]
And if we expand the statement of the problem and make the check more universal?

Let the author of the project decide whether there is enough component in the target system for his project to work.

Implement an element similar to an invocation, the result of which will tell you whether to continue the installation or not.

**Comment by SergeyMi37** [comment]
there is a proposal to implement a check in the preload
