### ISSUE TITLE
Make the option to setup REST apps without folders setup

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/zpm#35]
Sometimes we need only the name and dispatch class to setup the REST app.
But now ZPM needs PATH and Directory, and controls, if it exists in source, even it's not needed for the REST App.
example https://github.com/intersystems-community/RESTForms2/blob/master/module.xml
Let's simplify REST apps setup to give the option not use PATH and DIRECTORY params.

**Comment by timleavitt** [comment]
IIRC adding Generated="true" as a Resource attribute (indicating that there is no source involved) permits not including the path. Otherwise the assumption is that there should be CSP files copied from the resource's directory.

**Comment by evshvarov** [comment]
Hi Generated=true is connected to “no source involved”?
I mean it’s not very obvious

вт, 18 февр. 2020 г. в 15:02, Tim Leavitt <notifications@github.com>:

**Comment by timleavitt** [comment]
I agree that it's not obvious and should be clarified - just providing some history. :)

**Comment by evshvarov** [comment]
Sure, Tim! Thanks! Great to know that we have it addressed somehow already

вт, 18 февр. 2020 г. в 15:17, Tim Leavitt <notifications@github.com>:
