### ISSUE TITLE
Add an option to transfer parameters to modules installation

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/zpm#37]
For example the name of the REST application, or parameters for post-install methods

**Comment by evshvarov** [comment]
Could be implemented similar to what we have in %Installer: declare the defaults for parameters at the beginning of the module and substitute to transferred values in the call

**Comment by timleavitt** [comment]
You can already do this. In the command line, add -DParamName=Value - this goes into subscripts of the params array

**Comment by evshvarov** [comment]
wow. That's neat.
And how to declare the default parameter?

**Comment by timleavitt** [comment]
@evshvarov looks like the fork from the HS package manager was before that feature was added. It'd be fairly straightforward to port. I'll send internal references over an ISC-only back channel. ;)

**Comment by timleavitt** [comment]
The other missing piece for this pattern (which I'd recommend) would be support for arbitrary parameter names in %ZPM.PackageManager.Developer.Processor.Abstract:%Evaluate

Note that in command line -> COS, -DParamName.Something.Foo=Value translates to pParams("ParamName","Something","Foo") = "Value".

**Comment by evshvarov** [comment]
@timleavitt , how can I refer to the parameter inside the module?

**Comment by timleavitt** [comment]
You have access to the params array in the installer as well as resource processor class *Phase methods. If it's something that you want to persist, you can just stuff it in a global from the appropriate place (of those options).

**Comment by evshvarov** [comment]
Is it the right usage?
https://github.com/intersystems-community/ssl-client/blob/390619e2b739c63eecf38e816af241f0409a9739/module.xml#L12

**Comment by timleavitt** [comment]
@evshvarov I think so? Real test is, does it work? (I'm not super familiar with Invokes since that's not part of the original HS package manager.)
