### ISSUE TITLE
Issue with publishing declarative-objectscript package via OEX

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/zpm#53]
We received the following error while publishing your package declarative-objectscript:
ERROR #6901: XSLT XML Transformer Error: unable to determine file base pathname in at line 0 offset 0
[discussion](https://community.intersystems.com/post/appication-publication-failed-weird-error-message)

**Comment by nsolov** [comment]
I can't repeat this problem
I've published this package using a request as usual
I suppose it could be a problem with receiving data from github

**Comment by atygaev** [comment]
```We received the following error while publishing your package declarative-objectscript:
ERROR #5001: Invalid repository for this Package
InterSystems OpenExchange Team ```

Once again.

I checked "use README from github" and sent to approval.

**Comment by nsolov** [comment]
The problem with this package is due to the use "%" symbol in file names.
Now all "%" in filenames must be replaced to _.
