### ISSUE TITLE
Error install: blocksexplorer,  isc-apptools-admin

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems-community/zpm#74]
%SYS>zpm "list"
zpm 0.1.8

zpm: USER>install blocksexplorer
 
[blocksexplorer]        Reload START
[blocksexplorer]        Reload SUCCESS
[blocksexplorer]        Module object refreshed.
[blocksexplorer]        Validate START
[blocksexplorer]        Validate SUCCESS
[blocksexplorer]        Compile START
[blocksexplorer]        Compile FAILURE - ОШИБКА #5559: Определение класса Blocks.BlocksMap имеет ошибки, поэтому не может быть скомпилировано
  > ОШИБКА #5030: Возникла ошибка при компиляции класса Blocks.BlocksMap
ОШИБКА #5559: Определение класса Blocks.BlocksMap имеет ошибки, поэтому не может быть скомпилировано
  > ОШИБКА #5030: Возникла ошибка при компиляции класса Blocks.BlocksMap
ОШИБКА #5559: Определение класса Blocks.BlocksMap имеет ошибки, поэтому не может быть скомпилировано
  > ОШИБКА #5030: Возникла ошибка при компиляции класса Blocks.BlocksMap
zpm: USER>install webterminal

**Comment by daimor** [comment]
$zv?

**Comment by SergeyMi37** [comment]
in title

**Comment by SergeyMi37** [comment]
$zv=IRIS for Windows (x86-64) 2019.1.1 (Build 609U) Thu Sep 12 2019 22:26:55 EDT
2020.1 could not be installed, installation error on my laptops

**Comment by SergeyMi37** [comment]
Under docker in uигтег is also a mistake
...
%SYS>zpm
zpm: %SYS>list
zpm 0.1.7

zpm: %SYS>q

%SYS>zn "user"

USER>zpm
zpm: USER>find

registry https://pm.community.intersystems.com:
analyzethis 1.1.4
blocksexplorer 2.2.1
contest-rest-template 1.0.1
declarative-os 1.0.2
document-template 1.0.0
dsw 2.1.43
idp-dv 1.3.0
invoke-template 1.0.6
iris-history-monitor 1.1.0
iris-message-viewer 1.0.1
isc-dev 1.4.0
isc-tar 0.1.2
iteration 1.0.0
json-filter 1.4.2
mdx2json 2.2.0
objectscript-math 0.0.4
objectscript-openapi-definition 1.0.2
objectscript-package-example 1.0.0
objectscript-package-template 1.0.3
objectscript-starter-pack-example 1.0.0
output-capture 1.0.0
pivotsubscriptions 1.0.0
rest-template 1.0.5
restforms2 1.0.4
samples-aviation 1.0.0
samples-bi 1.0.1
sql-batch-outbound-adaptor 1.0.2
sqlbuilder 0.2.2
sslclient 1.0.1
swagger-ui 1.0.0
testcoverage 2.1.0
webterminal 4.9.2
zpm 0.1.8
zpm-registry 1.0.3
zpm: USER>
USER>

USER>

USER>zpm "install blocksexplorer"

[blocksexplorer]        Reload START
[blocksexplorer]        Reload SUCCESS
[blocksexplorer]        Module object refreshed.
[blocksexplorer]        Validate START
[blocksexplorer]        Validate SUCCESS
[blocksexplorer]        Compile START
[blocksexplorer]        Compile FAILURE - ERROR #5559: The class definition for class 'Blocks.BlocksMap' could not be parsed correctly, possibly due to non-matching {} or () characters. Edit the class and correct the problem.
  > ERROR #5030: An error occurred while compiling class 'Blocks.BlocksMap'
ERROR #5559: The class definition for class 'Blocks.BlocksMap' could not be parsed correctly, possibly due to non-matching {} or () characters. Edit the class and correct the problem.
  > ERROR #5030: An error occurred while compiling class 'Blocks.BlocksMap'
ERROR #5559: The class definition for class 'Blocks.BlocksMap' could not be parsed correctly, possibly due to non-matching {} or () characters. Edit the class and correct the problem.
  > ERROR #5030: An error occurred while compiling class 'Blocks.BlocksMap'
USER>

**Comment by SergeyMi37** [comment]
installed 2020.1
...
USER>zpm
zpm: USER>install blocksexplorer
 
[blocksexplorer]        Reload START
[blocksexplorer]        Reload SUCCESS
[blocksexplorer]        Module object refreshed.
[blocksexplorer]        Validate START
[blocksexplorer]        Validate SUCCESS
[blocksexplorer]        Compile START
[blocksexplorer]        Compile FAILURE - ОШИБКА #5559: Определение класса Blocks.BlocksMap имеет ошибки, поэтому не может быть скомпилировано
  > ОШИБКА #5030: Возникла ошибка при компиляции класса Blocks.BlocksMap
ОШИБКА #5559: Определение класса Blocks.BlocksMap имеет ошибки, поэтому не может быть скомпилировано
  > ОШИБКА #5030: Возникла ошибка при компиляции класса Blocks.BlocksMap
ОШИБКА #5559: Определение класса Blocks.BlocksMap имеет ошибки, поэтому не может быть скомпилировано
  > ОШИБКА #5030: Возникла ошибка при компиляции класса Blocks.BlocksMap
zpm: USER>
 
zpm: USER>q
 
USER>zw $zv
"IRIS for Windows (x86-64) 2020.1 (Build 215U) Mon Mar 30 2020 20:14:44 EDT"
 
USER>zn "%sys"
 
%SYS>zpm list
 
ZPM list
^
<UNDEFINED> *list
%SYS>zpm "list"
zpm 0.1.8

**Comment by SergeyMi37** [comment]
Symptoms of errors are very similar.
Moreover, when replicating on a local register, this error does not exist. Did you manage to figure it out?
----
zpm: IRISAPP>install isc-apptools-admin

[isc-apptools-admin]    Reload START
[isc-apptools-admin]    Reload SUCCESS
[isc-apptools-admin]    Module object refreshed.
[isc-apptools-admin]    Validate START
[isc-apptools-admin]    Validate SUCCESS
[isc-apptools-admin]    Compile START
[isc-apptools-admin]    Compile FAILURE - ERROR #5559: The class definition for class 'App.TabsPanelSample' could not be parsed correctly, possibly due to non-matching {} or () characters. Edit the class and correct the problem.
  > ERROR #5030: An error occurred while compiling class 'App.TabsPanelSample'
ERROR #5559: The class definition for class 'App.TabsPanelSample' could not be parsed correctly, possibly due to non-matching {} or () characters. Edit the class and correct the problem.
  > ERROR #5030: An error occurred while compiling class 'App.TabsPanelSample'
ERROR #5559: The class definition for class 'App.TabsPanelSample' could not be parsed correctly, possibly due to non-matching {} or () characters. Edit the class and correct the problem.
  > ERROR #5030: An error occurred while compiling class 'App.TabsPanelSample'

**Comment by SergeyMi37** [comment]
analysis showed that incomplete App.TabsPanelSample class is imported

**Comment by evshvarov** [comment]
@SergeyMi37 - close please?

**Comment by SergeyMi37** [comment]
yes
