### ISSUE TITLE
Add a flag "Description" to command "Search". If "Description" is not, then it is filled in the register from readme.MD repository

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems-community/zpm#83]

**Comment by evshvarov** [comment]
There is description in the module

**Comment by SergeyMi37** [comment]
I suggested adding a description and a short description to the atirbut module, from which information on the command would be scattered:

show a list of modules with a short description
>find -desc

show full description
>description <module_name>

**Comment by SergeyMi37** [comment]
If these attributes are not in the module.xml (as it is now), then take them from the repository readme.md file
