### ISSUE TITLE
Installing modules fails on IRIS Windows

### ISSUE THREAD

**Issue by pravinb1** [intersystems-community/zpm#9]
I'm getting an error if I try installing a module on IRIS for Windows:
```
zpm: APPSIGHT>install dsw

ERROR #5001: Error creating directory :
```

I traced this down to a line in ```##class(%ZPM.PackageManager.Developer.File).RemoveDirectoryTree()``` which calls ```##class(%File).NormalizeDirectory(##class(%File).TempFilename())```. This returns an empty string on IRIS because of a change in how the TempFilename method works.

**Comment by evshvarov** [comment]
Hi Pravin! What is the IRIS version you have? 
And It doesn't work on IRIS for Health ATM

**Comment by pravinb1** [comment]
Hello Evgeny! My $zversion is IRIS for Windows (x86-64) 2019.1 (Build 503U) Fri Feb 8 2019 14:23:04 EST

**Comment by pravinb1** [comment]
Also, the workaround I'm using now is to change this line:
`Set tEmptyDir = ##class(%File).NormalizeDirectory(##class(%File).TempFilename())`
to this:
`Set tEmptyDir = ##class(%File).NormalizeDirectory(##class(%File).TempFilename()_"t")`

**Comment by pravinb1** [comment]
#10

**Comment by evshvarov** [comment]
@pravinb1 - closing?

**Comment by pravinb1** [comment]
Yes, fine to close, thanks
