### ISSUE TITLE
Can't install on Cache for Windows (x86-64) 2018.1.1

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/zpm#90]
$zv: `Cache for Windows (x86-64) 2018.1.1 (Build 312_1_18859U) Tue Mar 19 2019 00:43:30 EDT`
Problem: `$$$FileTempDir` macro not found

**Comment by daimor** [comment]
We don't officially support Cache, only IRIS 2019.1+

**Comment by evshvarov** [comment]
Only for IRIS
