### ISSUE TITLE
add the ability to execute a mask command: zpm "install package-name*"

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems-community/zpm#96]
for command
install, unstall, publish, unpublish, ...

**Comment by daimor** [comment]
Nope, it's wrong usage. It should not be used this way

**Comment by SergeyMi37** [comment]
Why? in other packages this is a known practice.
But I agree that it is too early for zpm

**Comment by daimor** [comment]
any examples?

**Comment by SergeyMi37** [comment]
Yes, I’m wrong, I confused with another format:
install package1 package2 package3
