### ISSUE TITLE
Error on load /iris/app

### ISSUE THREAD

**Issue by diashenrique** [intersystems-community/zpm#97]
I'm testing the project to use zpm and during the testing phase to publish and deploy I'm getting the following error:

[iris-history-monitor]  Validate FAILURE - ERROR #5540: SQLCODE: -400 Message: ERROR #5002: ObjectScript error: <NOLINE>%0dsqlJ+5^%SQL.DICT.RoutineColumn.1
ERROR #5540: SQLCODE: -400 Message: ERROR #5002: ObjectScript error: <NOLINE>%0dsqlJ+5^%SQL.DICT.RoutineColumn.1
ERROR #5540: SQLCODE: -400 Message: ERROR #5002: ObjectScript error: <NOLINE>%0dsqlJ+5^%SQL.DICT.RoutineColumn.1

The repository is: https://github.com/diashenrique/iris-history-monitor

**Comment by nsolov** [comment]
I can not reproduce the problem.
Do you still have one?

**Comment by diashenrique** [comment]
> I can not reproduce the problem.
> Do you still have one?

No. Now it's okay. Evgeny informed us in the last week about the fix. 
Thanks
