### ISSUE TITLE
Improve error information for the case of publishing a package with the same version

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/zpm#98]
Now is the following:
"Publish FAILURE - ERROR #5001: Publishing module, something went wrong."

**Comment by daimor** [comment]
At the moment, there are no problems, in publishing the same version of the package. This particular error reported by any error on registry side.
So, best would be to investigate a particular package publishing process.

**Comment by daimor** [comment]
One of the issues possible right now, to get this error, is a too big package, like iris-history-monitor, which has size about 29 MB in tar.gz.
